UI: Remove external dependencies and formatting
postmanlabs/schemas pull request #22
Opened 2018-09-07 11:36 UTC by codenirvana

2018-09-07 14:07 UTC, godfrzero requested changes
I've refrained from suggesting anything that might trigger a refactor, and I'm assuming that only the header/footer have been touched.

To avoid repetitive work (and if it's sufficiently simple), I'd suggest using a layout.

2018-09-07 14:07 UTC, godfrzero commented on dist/index.mustache
> +
Unnecessary empty line.

2018-09-07 14:07 UTC, godfrzero commented on dist/index.mustache
> +<head>
Indentation! The `head` tag is a child of `html`. We indent children.

2018-09-07 14:07 UTC, godfrzero commented on dist/index.mustache
> +    <link rel="stylesheet" type="text/css" href="../../css/styles.css">
Can these two CSS files be combined?

2018-09-07 14:07 UTC, godfrzero commented on dist/index.mustache
> +        <span>&copy; 2018 Postdot Technologies, Inc.</span>
We don't want to update the 2018 every year. Is there no way to get the current year in here?

2018-09-07 14:07 UTC, godfrzero commented on dist/index.mustache
> +            ga('create', 'UA-43979731-4', 'auto');
TODO: Verify that this ID is still valid.

2018-09-07 14:11 UTC, codenirvana commented on dist/index.mustache
> +    <link rel="stylesheet" type="text/css" href="../../css/styles.css">
The first one is `docson` library's CSS and its override and our custom styles are added in `styles.css`.

2018-09-07 14:21 UTC, codenirvana commented on dist/index.mustache
> +            ga('create', 'UA-43979731-4', 'auto');
Yes, verifed 👍

2018-09-09 19:06 UTC, kunagpal requested changes

2018-09-09 19:06 UTC, kunagpal commented on dist/table_of_contents.mustache
> +      <script type="text/javascript">
This should be in the head: https://developers.google.com/tag-manager/quickstart

2018-09-10 06:26 UTC, kunagpal approved these changes

2018-09-10 06:29 UTC, merged