[DO NOT MERGE] Changed default draft version to 7
postmanlabs/schemas pull request #34
Opened 2018-11-07 22:14 UTC by kunagpal

- [ ] Remove the `DO NOT MERGE` prefix when all dependencies have been assessed.

2018-11-12 06:28 UTC, codenirvana requested changes
Directory structure to also follow `/:entity/:format/:version/:draft/` format?

2018-11-12 06:28 UTC, codenirvana commented on dist/index.mustache
> +      <link rel="stylesheet" type="text/css" href="{{{root}}}/css/styles.css">
Same change required in `table_of_contents.mustache` CSS path as well.

2018-11-12 06:30 UTC, kunagpal commented on dist/index.mustache
> +      <link rel="stylesheet" type="text/css" href="{{{root}}}/css/styles.css">
@codenirvana Yes, to be taken up in a separate pull request, which will be non-blocking on consumers.

2018-11-13 05:28 UTC, shamasis commented
How about completely decoupling the web directory structure and the schema directory structure?

2018-11-13 06:51 UTC, kunagpal commented
@shamasis The schema and generated web directory structures are essentially decoupled at this point.

2018-11-13 07:02 UTC, codenirvana approved these changes

2018-11-13 07:10 UTC, shamasis approved these changes

2018-11-13 07:32 UTC, merged