Add timings in Response
postmanlabs/schemas pull request #63
Opened 2019-02-07 08:16 UTC by vikiCoder

Update schemas of v1.0.0, v2.0.0 and v2.1.0 for both the drafts(4 & 7) to include timings information in response.

2019-02-07 08:17 UTC, vikiCoder commented
Please review the examples for draft-7 - v2.1.0 first. If those are okay, I'll do the same for others.

2019-02-08 14:44 UTC, kunagpal requested changes

2019-02-08 14:44 UTC, kunagpal commented on schemas/draft-07/v1.0.0/collection/request.json
> +            "description": "Set of timing information related to request and response in milliseconds"
Keep the title and description together as has been done in the rest of the changes above.

2019-02-10 14:02 UTC, kunagpal approved these changes

2019-02-10 14:03 UTC, merged